keymap = {}

keymap.find_files = "<leader>ff"
keymap.live_grep = "<leader>fg"
keymap.find_buffers = "<leader>fb"
keymap.find_help = "<leader>fh"
keymap.find_todo = "<leader>ft"

keymap.view_git = "<leader>vg"
keymap.view_tree = "<leader>vt"
keymap.view_workspaces = "<leader>vw"
keymap.view_debug = "<leader>vd"

keymap.go_to_references = "<leader>gr"
keymap.go_to_definition = "<leader>gd"
keymap.go_to_type_definition = "<leader>gD"
keymap.go_to_implementation = "<leader>gi"
keymap.lsp_code_action = "<leader>la"
keymap.lsp_format_files = "<leader>lf"
keymap.lsp_rename = "<leader>lr"
keymap.lsp_signature_help = "<C-k>"
keymap.lsp_hover = "K"

keymap.trouble_global = "<leader>qq"
keymap.trouble_local = "<leader>qQ"
keymap.trouble_todo = "<leader>qt"

keymap.debug_continue = "<F5>"
keymap.debug_step_over = "<F10>"
keymap.debug_step_into = "<F11>"
keymap.debug_step_out = "<F12>"
keymap.debug_toggle_breakpoint = "<leader>b"
keymap.debug_set_condotional_breakpoint = "<leader>B"
keymap.debug_set_log_point = "<leader>dp"
keymap.debug_repl = "<leader>dr"
keymap.debug_run_last = "<leader>dl"

keymap.project_build_all = "<leader>pb"
keymap.project_actions = "<leader>pa"
keymap.project_run_tests = "<leader>pt"
keymap.project_restore = "<leader>ps"
keymap.project_create_new_project = "<leader>pcn"
keymap.project_create_tamplate_file = "<leader>pct"
keymap.project_package_add = "<leader>ppa"
keymap.project_package_remove = "<leader>ppr"

keymap.surrounding_add = "gza"
keymap.surrounding_delete = "gzd"
keymap.surrounding_find = "gzf"
keymap.surrounding_find_left = "gzF"
keymap.surrounding_highlight = "gzh"
keymap.surrounding_replace = "gzr"
keymap.surrounding_update_n_lines = "gzn"
