local separator = package.config:sub(1, 1)
return {
    "nvim-telescope/telescope.nvim", tag = "0.1.8",
    dependencies = { "nvim-lua/plenary.nvim" },
    opts = {
        defaults = {
            file_ignore_patterns = {
                "%.dll$",
                "%.pdb$",
                "%.cm$",
                "%.bhc$",
                "%.obj$",
                "%.meta$",
                "%.prefab$",
                "%.asmdef$",
                "%.unity$",
                "%.asset$",
                "%.expr$",
                "%.exr$",
                "%.amin$",
                "%.lighting$",
                "%.controller$",
                "%.overrideController$",
                "%.mat$",
                "%.FBX$",
                "%.jpg",
                "%.png",
                "%.bmp",
                "Packages",
                "PackageChache",
                "Library",
                "obj",
                ".git" .. separator,
                ".github",
                ".vs",
            },
        },
        extensions = {
            workspaces = {
                keep_insert = true,
                path_hl = "String",
            },
        },
    },
    keys = {
        { keymap.find_files, function() require("telescope.builtin").find_files() end, desc = "Telescope find files" },
        { keymap.live_grep, function() require("telescope.builtin").live_grep() end, desc = "Telescope live grep" },
        { keymap.find_buffers, function() require("telescope.builtin").buffers() end, desc = "Telescope buffers" },
        { keymap.find_help, function() require("telescope.builtin").help_tags() end, desc = "Telescope help tags" },
    },
}
