local separator = package.config:sub(1, 1)
return {
    "nvim-telescope/telescope.nvim", tag = "0.1.8",
    dependencies = { "nvim-lua/plenary.nvim" },
    opts = {
        defaults = {
            file_ignore_patterns = {
                "%.dll$",
                "%.pdb$",
                "%.cm$",
                "%.bhc$",
                "%.obj$",
                "%.meta$",
                "%.prefab$",
                "%.asmdef$",
                "%.unity$",
                "%.asset$",
                "%.expr$",
                "%.exr$",
                "%.amin$",
                "%.lighting$",
                "%.controller$",
                "%.overrideController$",
                "%.mat$",
                "%.FBX$",
                "%.jpg",
                "%.png",
                "%.bmp",
                "Packages",
                "PackageChache",
                separator .. "Library" .. separator,
                separator .. "obj" .. separator,
                "%.git" .. separator,
                "%.git" .. separator,
                "%.github" .. separator,
                "%.vs" .. separator,
            },
        },
        extensions = {
            workspaces = {
                keep_insert = true,
                path_hl = "String",
            },
        },
    },
    keys = {
        { "<C-p>", function() require("telescope.builtin").find_files() end, desc = "Telescope find files" },
        { "<leader>ff", function() require("telescope.builtin").find_files() end, desc = "Telescope find files" },
        { "<leader>fg", function() require("telescope.builtin").live_grep() end, desc = "Telescope live grep" },
        { "<leader>fb", function() require("telescope.builtin").buffers() end, desc = "Telescope buffers" },
        { "<leader>fh", function() require("telescope.builtin").help_tags() end, desc = "Telescope help tags" },
    },
}
